### PR TITLE
Refresh plugin

### PR DESCRIPTION
**Pull request by basil**
Hi @alecharp, would you be interested in releasing a refreshed version of this plugin by any chance? This would help resolve some failures I'm seeing in BOM/PCT when running the tests for this plugin with a newer (stricter) version of PCT.

### CODE REVIEW

**Review by jetersen — APPROVED** [review]

**Comment by alecharp** [comment]
@basil I would have no problem releasing the plugin with your patch but I have no merge permission here.

**Review by alecharp — APPROVED** [review]

**Comment by jetersen** [comment]
That must be a mistake: https://github.com/jenkins-infra/repository-permissions-updater/blob/a1956df84408208af8bd03a1963ed08dbc166d05/permissions/plugin-mapdb-api.yml#L9 😓

**Comment by alecharp** [comment]
based on https://github.com/orgs/jenkinsci/teams/mapdb-api-plugin-developers, only @stephenc has permissions on this repository, but all members of `cloudbees-developers` group can release (https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-mapdb-api.yml)

**Comment by jetersen** [comment]
I think if you ask nicely over at https://github.com/jenkins-infra/helpdesk you would be able to get permissions :)

**Comment by alecharp** [comment]
everything can be resolved with jenkins-infra/helpdesk ;) https://github.com/jenkins-infra/helpdesk/issues/3077

**Comment by alecharp** [comment]
@basil: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/mapdb-api/1.0.9-28.vf251ce40855d/ and https://github.com/jenkinsci/mapdb-api-plugin/releases/tag/1.0.9-28.vf251ce40855d

**Comment by basil** [comment]
Thank you!

**Pull request merged**
